// <auto-generated />
namespace JayFashio_M.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class m88 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m88));
        
        string IMigrationMetadata.Id
        {
            get { return "202112110515381_m88"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
