// <auto-generated />
namespace JayFashio_M.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class vb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(vb));
        
        string IMigrationMetadata.Id
        {
            get { return "202202052059060_vb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
